name: Build backend base image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-backend-base.yaml
      - docker/backend-base/**
  workflow_dispatch:

jobs:
  publish-base-image:
    name: Build and publish base image
    permissions:
      packages: write
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Extract metadata for base image
        id: meta-base
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ghcr.io/evellama/evellama-backend-base
          tags: |
            type=edge,branch=main
          labels: |
            org.opencontainers.image.title=evellama-backend-base
            org.opencontainers.image.description="EVE Llama backend base image (not for deployment)"
            org.opencontainers.image.vendor="EVE Llama"
            org.opencontainers.image.documentation="https://github.com/evellama/evellama/blob/main/scripts/images/docker/backend-base/README.md"
            org.opencontainers.image.source="https://github.com/evellama/evellama/tree/main/scripts/images/docker/backend-base"
            org.opencontainers.image.licenses="MIT"
      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/backend-base
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
